services:
  ollama:
    container_name: frida-cortex
    build:
      context: ./inference
      dockerfile: Dockerfile
    image: frida-cortex:latest
    runtime: nvidia
    network_mode: host
    volumes:
      - ./inference:/ollama
    environment:
      - OLLAMA_MODELS=/ollama
    stdin_open: true
    tty: true
    entrypoint:
      ["/bin/bash", "-c", "/ollama/entrypoint.sh && tail -f /dev/null"]
