###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum

from pydantic import BaseModel, ConfigDict

from typing_extensions import TypeAlias, Literal
from typing import Dict, Generic, List, Optional, TypeVar, Union

from . import types
from .types import Checked, Check

###############################################################################
#
#  These types are used for streaming, for when an instance of a type
#  is still being built up and any of its fields is not yet fully available.
#
###############################################################################

T = TypeVar('T')
class StreamState(BaseModel, Generic[T]):
    value: T
    state: Literal["Pending", "Incomplete", "Complete"]


class AnswerQuestion(BaseModel):
    action: Optional[Literal["answer_question"]] = None

class CommandListLLM(BaseModel):
    """Robot command list model"""
    commands: List[Union["GoTo", "PickObject", "FindPersonByName", "FindPerson", "Count", "GetPersonInfo", "GetVisualInfo", "AnswerQuestion", "FollowPersonUntil", "GuidePersonTo", "GiveObject", "PlaceObject", "SayWithContext"]]

class Count(BaseModel):
    action: Optional[Literal["count"]] = None
    target_to_count: Optional[str] = None

class FindPerson(BaseModel):
    action: Optional[Literal["find_person"]] = None
    attribute_value: Optional[Union[Literal[""], str]] = None

class FindPersonByName(BaseModel):
    action: Optional[Literal["find_person_by_name"]] = None
    name: Optional[str] = None

class FollowPersonUntil(BaseModel):
    action: Optional[Literal["follow_person_until"]] = None
    destination: Optional[Union[Literal["cancelled"], str]] = None

class GetPersonInfo(BaseModel):
    action: Optional[Literal["get_person_info"]] = None
    info_type: Optional[Union[Literal["pose"], Literal["gesture"], Literal["name"], str]] = None

class GetVisualInfo(BaseModel):
    action: Optional[Literal["get_visual_info"]] = None
    measure: Optional[str] = None
    object_category: Optional[str] = None

class GiveObject(BaseModel):
    action: Optional[Literal["give_object"]] = None

class GoTo(BaseModel):
    action: Optional[Literal["go_to"]] = None
    location_to_go: Optional[Union[Literal["start_location"], str]] = None

class GuidePersonTo(BaseModel):
    action: Optional[Literal["guide_person_to"]] = None
    destination_room: Optional[str] = None

class PickObject(BaseModel):
    action: Optional[Literal["pick_object"]] = None
    object_to_pick: Optional[str] = None

class PlaceObject(BaseModel):
    action: Optional[Literal["place_object"]] = None

class SayWithContext(BaseModel):
    action: Optional[Literal["say_with_context"]] = None
    user_instruction: Optional[str] = None
    previous_command_info: Optional[Union[Literal["introduction"], str]] = None

class TaskExecutionResult(BaseModel):
    action: Optional[str] = None
    success: Optional[bool] = None
    result: Optional[str] = None
