###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import typing
from baml_py.baml_py import FieldType, EnumValueBuilder, EnumBuilder, ClassBuilder
from baml_py.type_builder import TypeBuilder as _TypeBuilder, ClassPropertyBuilder, ClassPropertyViewer, EnumValueViewer
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME


class TypeBuilder(_TypeBuilder):
    def __init__(self):
        super().__init__(classes=set(
          ["AnswerQuestion","CommandListLLM","Count","FindPerson","FindPersonByName","FollowPersonUntil","GetPersonInfo","GetVisualInfo","GiveObject","GoTo","GuidePersonTo","PickObject","PlaceObject","SayWithContext","TaskExecutionResult",]
        ), enums=set(
          []
        ), runtime=DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME)


    @property
    def AnswerQuestion(self) -> "AnswerQuestionAst":
        return AnswerQuestionAst(self)

    @property
    def CommandListLLM(self) -> "CommandListLLMAst":
        return CommandListLLMAst(self)

    @property
    def Count(self) -> "CountAst":
        return CountAst(self)

    @property
    def FindPerson(self) -> "FindPersonAst":
        return FindPersonAst(self)

    @property
    def FindPersonByName(self) -> "FindPersonByNameAst":
        return FindPersonByNameAst(self)

    @property
    def FollowPersonUntil(self) -> "FollowPersonUntilAst":
        return FollowPersonUntilAst(self)

    @property
    def GetPersonInfo(self) -> "GetPersonInfoAst":
        return GetPersonInfoAst(self)

    @property
    def GetVisualInfo(self) -> "GetVisualInfoAst":
        return GetVisualInfoAst(self)

    @property
    def GiveObject(self) -> "GiveObjectAst":
        return GiveObjectAst(self)

    @property
    def GoTo(self) -> "GoToAst":
        return GoToAst(self)

    @property
    def GuidePersonTo(self) -> "GuidePersonToAst":
        return GuidePersonToAst(self)

    @property
    def PickObject(self) -> "PickObjectAst":
        return PickObjectAst(self)

    @property
    def PlaceObject(self) -> "PlaceObjectAst":
        return PlaceObjectAst(self)

    @property
    def SayWithContext(self) -> "SayWithContextAst":
        return SayWithContextAst(self)

    @property
    def TaskExecutionResult(self) -> "TaskExecutionResultAst":
        return TaskExecutionResultAst(self)





class AnswerQuestionAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("AnswerQuestion")
        self._properties: typing.Set[str] = set([ "action", ])
        self._props = AnswerQuestionProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "AnswerQuestionProperties":
        return self._props


class AnswerQuestionViewer(AnswerQuestionAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class AnswerQuestionProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def action(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("action"))

    

class CommandListLLMAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("CommandListLLM")
        self._properties: typing.Set[str] = set([ "commands", ])
        self._props = CommandListLLMProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "CommandListLLMProperties":
        return self._props


class CommandListLLMViewer(CommandListLLMAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class CommandListLLMProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def commands(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("commands"))

    

class CountAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Count")
        self._properties: typing.Set[str] = set([ "action",  "target_to_count", ])
        self._props = CountProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "CountProperties":
        return self._props


class CountViewer(CountAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class CountProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def action(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("action"))

    @property
    def target_to_count(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("target_to_count"))

    

class FindPersonAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("FindPerson")
        self._properties: typing.Set[str] = set([ "action",  "attribute_value", ])
        self._props = FindPersonProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "FindPersonProperties":
        return self._props


class FindPersonViewer(FindPersonAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class FindPersonProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def action(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("action"))

    @property
    def attribute_value(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("attribute_value"))

    

class FindPersonByNameAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("FindPersonByName")
        self._properties: typing.Set[str] = set([ "action",  "name", ])
        self._props = FindPersonByNameProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "FindPersonByNameProperties":
        return self._props


class FindPersonByNameViewer(FindPersonByNameAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class FindPersonByNameProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def action(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("action"))

    @property
    def name(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("name"))

    

class FollowPersonUntilAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("FollowPersonUntil")
        self._properties: typing.Set[str] = set([ "action",  "destination", ])
        self._props = FollowPersonUntilProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "FollowPersonUntilProperties":
        return self._props


class FollowPersonUntilViewer(FollowPersonUntilAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class FollowPersonUntilProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def action(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("action"))

    @property
    def destination(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("destination"))

    

class GetPersonInfoAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("GetPersonInfo")
        self._properties: typing.Set[str] = set([ "action",  "info_type", ])
        self._props = GetPersonInfoProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "GetPersonInfoProperties":
        return self._props


class GetPersonInfoViewer(GetPersonInfoAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class GetPersonInfoProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def action(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("action"))

    @property
    def info_type(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("info_type"))

    

class GetVisualInfoAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("GetVisualInfo")
        self._properties: typing.Set[str] = set([ "action",  "measure",  "object_category", ])
        self._props = GetVisualInfoProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "GetVisualInfoProperties":
        return self._props


class GetVisualInfoViewer(GetVisualInfoAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class GetVisualInfoProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def action(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("action"))

    @property
    def measure(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("measure"))

    @property
    def object_category(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("object_category"))

    

class GiveObjectAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("GiveObject")
        self._properties: typing.Set[str] = set([ "action", ])
        self._props = GiveObjectProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "GiveObjectProperties":
        return self._props


class GiveObjectViewer(GiveObjectAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class GiveObjectProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def action(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("action"))

    

class GoToAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("GoTo")
        self._properties: typing.Set[str] = set([ "action",  "location_to_go", ])
        self._props = GoToProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "GoToProperties":
        return self._props


class GoToViewer(GoToAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class GoToProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def action(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("action"))

    @property
    def location_to_go(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("location_to_go"))

    

class GuidePersonToAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("GuidePersonTo")
        self._properties: typing.Set[str] = set([ "action",  "destination_room", ])
        self._props = GuidePersonToProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "GuidePersonToProperties":
        return self._props


class GuidePersonToViewer(GuidePersonToAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class GuidePersonToProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def action(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("action"))

    @property
    def destination_room(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("destination_room"))

    

class PickObjectAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("PickObject")
        self._properties: typing.Set[str] = set([ "action",  "object_to_pick", ])
        self._props = PickObjectProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "PickObjectProperties":
        return self._props


class PickObjectViewer(PickObjectAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class PickObjectProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def action(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("action"))

    @property
    def object_to_pick(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("object_to_pick"))

    

class PlaceObjectAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("PlaceObject")
        self._properties: typing.Set[str] = set([ "action", ])
        self._props = PlaceObjectProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "PlaceObjectProperties":
        return self._props


class PlaceObjectViewer(PlaceObjectAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class PlaceObjectProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def action(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("action"))

    

class SayWithContextAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("SayWithContext")
        self._properties: typing.Set[str] = set([ "action",  "user_instruction",  "previous_command_info", ])
        self._props = SayWithContextProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "SayWithContextProperties":
        return self._props


class SayWithContextViewer(SayWithContextAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class SayWithContextProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def action(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("action"))

    @property
    def user_instruction(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("user_instruction"))

    @property
    def previous_command_info(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("previous_command_info"))

    

class TaskExecutionResultAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("TaskExecutionResult")
        self._properties: typing.Set[str] = set([ "action",  "success",  "result", ])
        self._props = TaskExecutionResultProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "TaskExecutionResultProperties":
        return self._props


class TaskExecutionResultViewer(TaskExecutionResultAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class TaskExecutionResultProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def action(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("action"))

    @property
    def success(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("success"))

    @property
    def result(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("result"))

    




__all__ = ["TypeBuilder"]