###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum

from pydantic import BaseModel, ConfigDict

from typing_extensions import TypeAlias, Literal
from typing import Dict, Generic, List, Optional, TypeVar, Union


T = TypeVar('T')
CheckName = TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, Generic[T,CheckName]):
    value: T
    checks: Dict[CheckName, Check]

def get_checks(checks: Dict[CheckName, Check]) -> List[Check]:
    return list(checks.values())

def all_succeeded(checks: Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))



class AnswerQuestion(BaseModel):
    action: Literal["answer_question"]

class CommandListLLM(BaseModel):
    """Robot command list model"""
    commands: List[Union["GoTo", "PickObject", "FindPersonByName", "FindPerson", "Count", "GetPersonInfo", "GetVisualInfo", "AnswerQuestion", "FollowPersonUntil", "GuidePersonTo", "GiveObject", "PlaceObject", "SayWithContext"]]

class Count(BaseModel):
    action: Literal["count"]
    target_to_count: str

class FindPerson(BaseModel):
    action: Literal["find_person"]
    attribute_value: Union[Literal[""], str]

class FindPersonByName(BaseModel):
    action: Literal["find_person_by_name"]
    name: str

class FollowPersonUntil(BaseModel):
    action: Literal["follow_person_until"]
    destination: Union[Literal["cancelled"], str]

class GetPersonInfo(BaseModel):
    action: Literal["get_person_info"]
    info_type: Union[Literal["pose"], Literal["gesture"], Literal["name"], str]

class GetVisualInfo(BaseModel):
    action: Literal["get_visual_info"]
    measure: str
    object_category: str

class GiveObject(BaseModel):
    action: Literal["give_object"]

class GoTo(BaseModel):
    action: Literal["go_to"]
    location_to_go: Union[Literal["start_location"], str]

class GuidePersonTo(BaseModel):
    action: Literal["guide_person_to"]
    destination_room: str

class PickObject(BaseModel):
    action: Literal["pick_object"]
    object_to_pick: str

class PlaceObject(BaseModel):
    action: Literal["place_object"]

class SayWithContext(BaseModel):
    action: Literal["say_with_context"]
    user_instruction: str
    previous_command_info: Union[Literal["introduction"], str]

class TaskExecutionResult(BaseModel):
    action: str
    success: bool
    result: str
